有时服务器报错，并不能知道问题在哪，我们可以借用trycatch的特性来捕获错误。

```js
try {
    fs.writeFileSync('./models/db/users.json',JSON.stringify(users))
    return true
} catch (error) {
    console.log(error)
    return false
}

try {
    //这里写我们正常的业务逻辑
    const users = findAll()   //在修改const创建的users时会报错
    const {id} = req.body
    users = users.filter(item=> item.id != id)
    save(users)
    res.send({
        code:1,
        msg:'删除成功',
    })
    
} catch (error) {
    //try里捕获到错误后会进入catch
    console.log(error)     //报错会在此处进行一个输出，
    res.send({
        code:0,
        msg:'服务器错误',
    })
}
```

try&catch还可以解决，程序报错卡死的问题。因为捕获到错误后并不会报红，只会进入catch进行输出。

